name: Deploy Frontend to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          known_hosts: ${{ secrets.EC2_KNOWN_HOSTS }}

      - name: Deploy via SSH
        run: |
          # Copy files to EC2
          scp -r -o StrictHostKeyChecking=no . ubuntu@${{ secrets.EC2_HOST }}:~/fullstack-app/frontend

          # Build and run frontend
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "
          sudo docker rm frontend
            cd ~/fullstack-app/frontend
            sudo docker build -t frontend .
            sudo docker run -d --name frontend -p 80:80 --restart unless-stopped frontend
          "
