name: Deploy Frontend to EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          known_hosts: ${{ secrets.EC2_KNOWN_HOSTS }}

      - name: Copy Files to EC2
        run: |
          scp -o StrictHostKeyChecking=no deploy.tar.gz ubuntu@${{ secrets.EC2_HOST }}:~/fullstack-deployment/
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "
          cd ~/fullstack-deployment
          tar -xzf deploy.tar.gz -C frontend/
          rm deploy.tar.gz
          "

          rm deploy.tar.gz

      - name: Build and Run Frontend on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "
            cd ~/fullstack-deployment/frontend
            docker build -t frontend .
            docker stop frontend-container || true
            docker rm frontend-container || true
            docker run -d --name frontend-container -p 80:80 --network fullstack-network --restart unless-stopped frontend
          "

