name: Deploy Frontend to EC2

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          known_hosts: ${{ secrets.EC2_KNOWN_HOSTS }}

      - name: Create and Transfer Deployment Archive
        run: |
          # Create deployment directory if it doesn't exist
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "mkdir -p ~/fullstack-deployment/frontend"

          # Create tar archive of current commit (excluding .git)
          tar --exclude='.git' --exclude='node_modules' -czf deploy.tar.gz .

          # Transfer archive to EC2
          scp -o StrictHostKeyChecking=no deploy.tar.gz ubuntu@${{ secrets.EC2_HOST }}:~/fullstack-deployment/

          # Extract and clean up on EC2
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "
            cd ~/fullstack-deployment
            tar -xzf deploy.tar.gz -C frontend/
            rm deploy.tar.gz
          "

          # Clean up locally
          rm deploy.tar.gz

      - name: Build and Run Frontend Container
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "
            cd ~/fullstack-deployment/frontend
            docker build -t frontend .
            docker stop frontend-container || true
            docker rm frontend-container || true
            docker run -d --name frontend-container -p 80:80 --network fullstack-network --restart unless-stopped frontend
          "
